{{- if (.Capabilities.APIVersions.Has "route.openshift.io/v1") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kubetoy
  labels:
    app: kubetoy-app
spec:
  to:
    kind: Service
    name: kubetoy-service
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
  {{- end }}
