name: ci

on:
  push:
    branches:
      - "master"
    tags:
      - 'v*'
    paths:
      - app/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            jwcarmichael/kubetoy
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            #type=semver,pattern={{major}}.{{minor}}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          install: true
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          tags: ${{ steps.meta.outputs.tags }}
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}

    update-kustomization-yaml:
      name: "Update Kustomization.yaml File"
      needs: "docker"
      runs-on: ubuntu-latest
      steps:
        - name: "Git Checkout"
          uses: actions/checkout@v4
        - name: "Update Deployment Image Tag"
          working-directory: "deployment/all-in-one"
          run: |
            kustomize edit set image new-image=docker.io/jwcarmichael/kubetoy:${{ steps.meta.outputs.tags }}
        - name: "Commit Updated Image Tag To GitHub Rep"
          run: |
            git config --global user.name="jwcarmichael"
            git config --global user.email="james.carmichael@hcl.com"
            git commit -am "feat: Update deployment image tag to $ {{ steps.meta.outputs.tags }}
            git push
            
            
