name: Create DevOps Deploy Component Version

on:
  push:
    branches:
      - master
    paths:
      - deployment/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    = name: Create artifact to add to component
      id: artifact
      run: date > /tmp/artifacts/date.txt
    - name: Set short_commit_id
      id: vars
      run: echo "short_commit_id=$(echo ${{ github.event.head_commit.id }} | cut -c1-7)" >> "$GITHUB_ENV"
    - name: Create Component Version
      uses: HCL-TECH-SOFTWARE/devops-deploy-createcomponentversion-action@pr/DEPLOY15417
      with:
        component: 'Kubetoy'
        versionname: '${{ env.short_commit_id }}:${{ github.event.head_commit.message }}'
        description: 'Commit ID: ${{ github.event.head_commit.id }} Repository URL: ${{ github.repositoryUrl }}'
        link: '${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.head_commit.id }}'
        base: /tmp/artifacts
        hostname: '35.245.205.184'
        port: '8443'
        authToken: '${{ secrets.DEVOPS_DEPLOY_AUTHTOKEN }}'
