name: Create DevOps Deploy Component Version

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Create Component Version
      uses: HCL-TECH-SOFTWARE/devops-deploy-createcomponentversion-action@v1.0
      with:
        component: 'Kubetoy'
        versionname: '${{ github.event.head_commit.message }}'
        description: 'Commit ID: ${{ github.event.head_commit.id }} Repository URL: ${{ github.repositoryUrl }}'
        link: '${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.head_commit.id }}'
        hostname: 'openshift-gitops-server-openshift-gitops.ucd-ocp12-e3a3d814b8ff2369cc3d5b63c99b22ba-0000.us-east.containers.appdomain.cloud'
        port: '443'
        authToken: '90449ba9-f92f-40aa-8fe3-6eab837beab8'
