name: Create DevOps Deploy Component Version

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set short_commit_id
      id: vars
      run: echo "short_commit_id=$(echo ${{ github.event.head_commit.id }} | cut -c1-7)" >> "$GITHUB_ENV"
    - name: Test short_commit_id
      run: echo $short_commit_id
    - name: Create Component Version
      uses: HCL-TECH-SOFTWARE/devops-deploy-createcomponentversion-action@v1.0
      with:
        component: 'Kubetoy'
        versionname: '${{ env.short_commit_id }}:${{ github.event.head_commit.message }}'
        description: 'Commit ID:  Repository URL: ${{ github.repositoryUrl }}'
        link: '${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.head_commit.id }}'
        hostname: 'ucd80001163934-ibm-ucd-prod-ucd80001163934.ucd-ocp12-e3a3d814b8ff2369cc3d5b63c99b22ba-0000.us-east.containers.appdomain.cloud'
        port: '443'
        authToken: '${{ secrets.DEVOPS_DEPLOY_AUTHTOKEN }}'
