name: Test udclient support (Real)

on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test udclient support
    steps:
      - name: Create artifacts to add to component
        id: create-artifacts
        run: mkdir /tmp/artifacts && date > /tmp/artifacts/date.txt &&  ls -la > /tmp/artifacts/filelisting.txt
      - name: Set short_commit_id
        id: vars
        run: echo "short_commit_id=$(echo ${{ github.event.head_commit.id }} | cut -c1-7)" >> "$GITHUB_ENV"
      - name: Set optional global flags for udclient command
        id: set-optional-global-flags
        run: |
          echo "UC_TLS_VERIFY_CERTS=false" >> "$GITHUB_ENV"
      - uses: HCL-TECH-SOFTWARE/devops-deploy-createcomponentversion-action@v2devel
        with:
          component: 'Kubetoy'
          versionname: '${{ env.short_commit_id }}:${{ github.event.head_commit.message }}'
          description: 'Commit ID: ${{ github.event.head_commit.id }} Repository URL: ${{ github.repositoryUrl }}'
          linkName: 'Test username:password'
          link: '${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.head_commit.id }}'
          base: /tmp/artifacts
          offset: baseball/schedule
          versionProperties: |-
            Prop1:${{ env.short_commit_id }}:false
            Prop2:${{ github.event.head_commit.message }}:false
            Prop3:TestSecure:false
            Prop4:TestSecure:false
          hostname: '35.245.205.184'
          port: '8443'
          #authToken: '${{ secrets.DEVOPS_DEPLOY_AUTHTOKEN }}'
          username: 'admin'
          password: '${{ secrets.DEVOPS_DEPLOY_ADMIN_PASSWORD }}'
