name: Test udclient support

on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test udclient support
    steps:
      - name: Create artifacts to add to component
        id: create-artifacts
        run: mkdir /tmp/artifacts && date > /tmp/artifacts/date.txt
      - name: Set short_commit_id
        id: vars
        run: echo "short_commit_id=$(echo ${{ github.event.head_commit.id }} | cut -c1-7)" >> "$GITHUB_ENV"
      - uses: jwcarmichael12/test-composite-action@main
        with:
          component: 'Kubetoy'
          versionname: '${{ env.short_commit_id }}:${{ github.event.head_commit.message }}'
          description: 'Commit ID: ${{ github.event.head_commit.id }} Repository URL: ${{ github.repositoryUrl }}'
          linkName: 'James'
          link: '${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.head_commit.id }}'
          urlType: 'https:'
          base: /tmp/artifacts
          hostname: '35.245.205.184'
          port: '8443'
          authToken: '${{ secrets.DEVOPS_DEPLOY_AUTHTOKEN }}'
